[project]
name = "sample-mcp-server"
version = "0.1.0"
description = "Just a sample mcp server for testing purpose"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=1.26.0",
]

[project.scripts]
mcp-server= "mcpserver.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir={"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]